# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

simulate_networks_fit <- function(adjacency, dim, theta, n_update = 1000000L, n_cores = 4L, nsim = 1L, burnin = 1000L, log_change = TRUE) {
    .Call('_pergm_simulate_networks_fit', PACKAGE = 'pergm', adjacency, dim, theta, n_update, n_cores, nsim, burnin, log_change)
}

simulate_networks_fit_nw <- function(adjacency, dim, theta, n_update = 1000000L, n_cores = 4L, nsim = 1L, burnin = 1000L, log_change = TRUE) {
    .Call('_pergm_simulate_networks_fit_nw', PACKAGE = 'pergm', adjacency, dim, theta, n_update, n_cores, nsim, burnin, log_change)
}

summary_stats_log_c <- function(mat, dim, n_cores) {
    .Call('_pergm_summary_stats_log_c', PACKAGE = 'pergm', mat, dim, n_cores)
}

